version: "3"
services:
  app:
    build: .
    command: yarn start:dev
    image: node:lts-alpine
    env_file: .env.development
    volumes:
      - .:/usr/src/app
    ports:
      - 9000:9000

  db:
    image: postgres:11-alpine
    env_file: .env.development
    environment:
      - TZ=America/Los_Angeles
      - PGTZ=America/Los_Angeles
    volumes:
      - ./sql/init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
