-- CREATE LOGIN USERS
CREATE USER ${POSTGRES_APP_ADMIN_USER} LOGIN INHERIT IN ROLE onebrand_administrator_role ENCRYPTED PASSWORD "'"${POSTGRES_APP_ADMIN_PASSWORD}"';"
CREATE USER ${POSTGRES_APP_USER} LOGIN INHERIT IN ROLE onebrand_read_write_role ENCRYPTED PASSWORD "'"${POSTGRES_APP_PASSWORD}"';"
CREATE USER ${POSTGRES_READONLY_USER} LOGIN INHERIT IN ROLE onebrand_read_only_role ENCRYPTED PASSWORD "'"${POSTGRES_READONLY_PASSWORD}"';"
